export const dataList = [
  {
    id: 1,
    title: "Palm Harbour",
    adress: "27 Road parl, saint mariam",
    city: "Kolkata",
    type: "House",
    freeFrom: "28/08/2023",
    bed: 4,
    bathroom: 2,
    area: "4x7",

    price: 2500,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwDVnR2KuePkwgMZce_ChJ6zZDx6cU6r3k9w&usqp=CAU",
  },
  {
    id: 2,
    title: "Door Urban",
    adress: "95 Road heb, bibadi bag , kolkata",
    city: "Kolkata",
    type: "Hotel",
    freeFrom: "13/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",

    price: 1000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPn9XoJB1m-GnGtNlXIrzudOODYtZ3jfJebA&usqp=CAU",
  },
  {
    id: 3,
    title: "chow",
    adress: "92 Road heb, bibadi bag , kolkata",
    city: "Kolkata",
    type: "House",
    freeFrom: "12/08/2023",
    bed: 2,
    bathroom: 1,
    area: "5x8",
    price: 2000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrnTChk1dUKbcTVyPuI2KK4nGgx4jKSS07Uw&usqp=CAU",
  },
  {
    id: 4,
    title: "Anand vella",
    adress: "35 Road parl, saint mariam",
    city: "Kolkata",
    type: "Hotel",
    freeFrom: "10/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",
    price: 800,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNw2B5VESQ985PVK1Zn82q6mI9S0H-v2Yz1Q&usqp=CAU",
  },
  {
    id: 5,
    title: "Tossor",
    adress: "85 coloni street , Lakshminagar , Saltlake",
    city: "Bidhan Nagar",
    type: "Hotel",
    freeFrom: "16/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",
    price: 2000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpG4fFxesz8MjtBOcI3cxvFtJUgNDtPOIpvw&usqp=CAU",
  },
  {
    id: 6,
    title: "Stories Stair",
    adress: "Black heart road, kanhainagar ",
    city: "Kolkata",
    type: "House",
    freeFrom: "12/08/2023",
    bed: 2,
    bathroom: 1,
    area: "5x8",
    price: 500,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlV1WP3PL8NQQIc7-dV6oH9OP3iDL9m6Af3w&usqp=CAU",
  },
  {
    id: 7,
    title: "Nacho Chemb",
    adress: "15 street , kanhainagar ",
    city: "Bidhan Nagar",
    type: "House",
    freeFrom: "12/08/2023",
    bed: 4,
    bathroom: 2,
    area: "4x7",

    price: 2200,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVLytlSBL1ZYPM5UhvcrDAW0172aGqQqtmPw&usqp=CAU",
  },
  {
    id: 8,
    title: "Mushroom",
    adress: "15 coloni street , Lakshminagar , Saltlake",
    city: "Bidhan Nagar",
    type: "Hotel",
    freeFrom: "13/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",
    price: 1000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq05mnIddSO9QnrhaBleiFR_a5iM-BRsmQYw&usqp=CAU",
  },
  {
    id: 9,
    title: "Shitake",
    adress: "Oxford Road, Bidhannagar ",
    city: "Sealda",
    type: "House",
    freeFrom: "15/08/2023",
    bed: 4,
    bathroom: 2,
    area: "4x7",

    price: 2750,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxs2vGPru_X1hx6HlaS357KZrh9eHHXDSsow&usqp=CAU",
  },
  {
    id: 10,
    title: "Pestos",
    adress: "Hage House street , Alia University",
    city: "Sealda",
    type: "Hotel",
    freeFrom: "15/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",
    price: 2980,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnw2CZ6vY_Rup_70SLnBLHCUqAHavjqpmhFg&usqp=CAU",
  },
  {
    id: 11,
    title: "Brusch",
    adress: "Eden Park , Park circus",
    city: "Sealda",
    type: "House",
    freeFrom: "17/08/2023",
    bed: 2,
    bathroom: 1,
    area: "5x8",
    price: 2000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNuHP8xLdEqnO5B8bXCZBeOTzC6RfrgONhMA&usqp=CAU",
  },
  {
    id: 12,
    title: "Dim Suns",
    adress: "Kolkata mediacal street , Shealda",
    city: "Sealda",
    type: "Hotel",
    freeFrom: "11/08/2023",
    bed: 5,
    bathroom: 3,
    area: "9x8",
    
    price: 1000,
    coverSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9U7ej43-ej9vZT6F0K5fhzG2NL2f3yiT0Kw&usqp=CAU",
  },
];
